CREATE TABLE IF NOT EXISTS casts (
  id CHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  dob DATE NULL,
  nationality VARCHAR(100) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
